name: algorithm-m

on:
  push:
    paths:
    - '.github/workflows/algorithm-m.yaml'
    - 'language/**'
    - 'algorithm-m/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use npm v7
        run: npm i -g npm@7

      - name: 'language: Install dependencies'
        working-directory: language
        run: npm ci
      - name: 'language: Build'
        working-directory: language
        run: npm run build --if-present

      - name: 'algorithm-m: Install dependencies'
        working-directory: algorithm-m
        run: npm ci
      - name: 'algorithm-m: Lint'
        working-directory: algorithm-m
        run: npm run lint --if-present
      - name: 'algorithm-m: Build'
        working-directory: algorithm-m
        run: npm run build --if-present
      - name: 'algorithm-m: Test'
        working-directory: algorithm-m
        run: npm run test --if-present