name: CI

on:
  push:
    paths:
      - '.github/workflows/ci.yaml'
      - 'language/**'
      - 'algorithm-w/**'
      - 'algorithm-m/**'
      - 'algorithm-w-prime/**'
      - 'web/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build, Lint and Test
        run: |
          npm run build
          npm run lint
          npm run test

      # Deploy web app if on master branch
      - name: Deploy web
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/build
