name: language

on:
  push:
    paths:
    - '.github/workflows/language.yaml'
    - 'language/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use npm v7
        run: npm i -g npm@7

      - name: 'language: Install dependencies'
        working-directory: language
        run: npm ci
      - name: 'language: Lint'
        working-directory: language
        run: npm run lint --if-present
      - name: 'language: Build'
        working-directory: language
        run: npm run build --if-present
      - name: 'language: Test'
        working-directory: language
        run: npm run test --if-present