name: web

on:
  push:
    paths:
    - '.github/workflows/web.yaml'
    - 'language/**'
    - 'algorithm-w/**'
    - 'web/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use npm v7
        run: npm i -g npm@7

      - name: 'language: Install dependencies'
        working-directory: language
        run: npm ci
      - name: 'language: Build'
        working-directory: language
        run: npm run build --if-present

      - name: 'algorithm-w: Install dependencies'
        working-directory: algorithm-w
        run: npm ci
      - name: 'algorithm-w: Build'
        working-directory: algorithm-w
        run: npm run build --if-present

      - name: 'web: Install dependencies'
        working-directory: web
        run: npm ci
      - name: 'web: Lint'
        working-directory: web
        run: npm run lint --if-present
      - name: 'web: Build'
        working-directory: web
        run: npm run build --if-present
      - name: 'web: Test'
        working-directory: web
        run: npm run test --if-present
      - name: 'web: Deploy'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/build